### ISSUE TITLE
missing notification when screenshots are enabled

### ISSUE THREAD

**Issue by 45656456kawai** [IceQ1337/SteamBanChecker#13]
I noticed 2 bans in the cmd but no notification on telegram and screenshot folder is also empty.

**Comment by IceQ1337** [comment]
Is there any error in the console and can you check if your config and messages are up to date?

**Comment by 45656456kawai** [comment]
Yes i have double-checked the config file and its correct.

There's no error in the console it says profile has banned vac but no notifiction or screenshot in the folder.

but if i start the older script (without ss function) it instantly sends the notification about the same banned user.

So idk what could be wrong with the latest script.

**Comment by IceQ1337** [comment]
What about the message files?  
And check if you get a message when profile screenshots are disabled.

Can you attach the directory as a .zip file here, please?  
Make sure to remove your API Keys from the config, the node_modules folder and your .db files first.

Script is definitely working on multiple machines for me 🤔

**Comment by 45656456kawai** [comment]
https://filebin.net/2bhmzh25tm54k5fx/zipp.rar?t=ho5xnls5

**Comment by IceQ1337** [comment]
Your version is one commit behind (https://github.com/IceQ1337/SteamBanChecker/commit/0bacfcdf92e8de20829529621c3a774347fc80f9), but should (and does) still work regardless.  

Which version of Node.js and NPM is installed? `node -v` `npm -v`
Are you running it on a windows or linux machine?
Have you checked if you get any messages when screenshots are disabled?

In addition, an interval of one minute could potentially cause problems if you have a large amount of entries. An interval of 5 minutes should be enough if you want to be informed quickly.

**Comment by 45656456kawai** [comment]
node -v  v12.9.1
npm -v   6.10.2

Widnows
Haven't

1min interval works just fine with the precious 1.1.1 version and I guess it works fine in 2.0 as well since in console I can see banned profiles its just that I don't get notified by telegram.

**Comment by 45656456kawai** [comment]
added banned profiles in database and set inteval to 5 and ss false
opened the script and nothing happened it didn't even notify the profile is banned not even in the console

did the same on version 1.1.1 and as soon i opened the script it sent notification on telegram.

**Comment by IceQ1337** [comment]
Can you insert the following code in line 61 (server.js) and test if you get a message from your bot?  
``Telegram.sendMessage(`Ban:\nType: ${type}\nProfile: ${profileURL}`);``

**Comment by 45656456kawai** [comment]
Database.updateProfile(player.SteamId, updateData);
    
    const profileURL = SteamAPI.profileURL + player.SteamId;

    if (typeCommunity) {
        Telegram.sendMessage(Utility.replaceMessageString(Messages.profileCommunityBanned, { '%PROFILEURL%': profileURL }), users);


after


Database.updateProfile(player.SteamId, updateData);
    
    const profileURL = SteamAPI.profileURL + player.SteamId;
Telegram.sendMessage(`Ban:\nType: ${type}\nProfile: ${profileURL}`);
    if (typeCommunity) {
        Telegram.sendMessage(Utility.replaceMessageString(Messages.profileCommunityBanned, { '%PROFILEURL%': profileURL }), users);

nothing its still saying  Checking 15 profiles. even though 2 of em already banned

**Comment by IceQ1337** [comment]
Can you show me the content of your profiles.db and give me the SteamID64 of the two profiles?

**Comment by 45656456kawai** [comment]
for the sake of testing i grabbed banned profiles and added those in the new and old scripts but only 1.1.1 seems to be working fine for me

here's the db

{"$$indexCreated":{"fieldName":"SteamID","unique":true,"sparse":false}}
{"SteamID":"76561198345895322","CommunityBanned":false,"VACBanned":false,"NumberOfVACBans":0,"NumberOfGameBans":2,"Tracked":true,"Users":[911919489],"_id":"BeS8I3PHTeiUMPkR"}
{"SteamID":"76561198399083066","CommunityBanned":false,"VACBanned":false,"NumberOfVACBans":0,"NumberOfGameBans":1,"Tracked":true,"Users":[911919489],"_id":"4eBzZfXErAmDGci5"}

**Comment by IceQ1337** [comment]
The Steam API returned the following result:
```
{
  "players": [
    {
      "SteamId": "76561198345895322",
      "CommunityBanned": false,
      "VACBanned": false,
      "NumberOfVACBans": 0,
      "DaysSinceLastBan": 0,
      "NumberOfGameBans": 2,
      "EconomyBan": "none"
    },
    {
      "SteamId": "76561198399083066",
      "CommunityBanned": false,
      "VACBanned": false,
      "NumberOfVACBans": 0,
      "DaysSinceLastBan": 0,
      "NumberOfGameBans": 1,
      "EconomyBan": "none"
    }
  ]
}
```

`NumberOfGameBans` is already set to 2 and 1 in your profiles.db, but must be 1 and 0 in order to get a notification for these profiles. I assume you have done that right? If you didn't, thats why you receive no notification. 

The code  should be added like this:
```
const profileURL = SteamAPI.profileURL + player.SteamId;
Telegram.sendMessage(`Ban:\nType: ${type}\nProfile: ${profileURL}`);
```

**Comment by 45656456kawai** [comment]
I added the code like that now and changed the db files

{
  "players": [
    {
      "SteamId": "76561198345895322",
      "CommunityBanned": false,
      "VACBanned": false,
      "NumberOfVACBans": 0,
      "DaysSinceLastBan": 0,
      "NumberOfGameBans": o,
      "EconomyBan": "none"
    },
    {
      "SteamId": "76561198399083066",
      "CommunityBanned": false,
      "VACBanned": false,
      "NumberOfVACBans": 0,
      "DaysSinceLastBan": 0,
      "NumberOfGameBans": 0,
      "EconomyBan": "none"
    }
  ]
}

voila it worked i got the notification however no screenshot in telegram or in the folder. It's set as true in the config

Edit- without this code I don't get any notification at all.
Telegram.sendMessage(`Ban:\nType: ${type}\nProfile: ${profileURL}`);

**Comment by IceQ1337** [comment]
Can you try that again with profile screenshots being disabled?

**Comment by 45656456kawai** [comment]
notification working fine after editing the server file but screenshot not working

**Comment by IceQ1337** [comment]
So the reason for this issue is that no screenshots are taken, but it is strange that there is no error.  

Can you please run `npm update` and `npm install` and check if it's downloading something?  
If that doesn't help, try a complete re-install of this version.

**Comment by 45656456kawai** [comment]
installed fresh and updated npm now its working fine :) cheers
