### ISSUE TITLE
Add Profile Screenshots Back In

### ISSUE THREAD

**Issue by IceQ1337** [IceQ1337/SteamBanChecker#6]
Profile Screenshots were removed in https://github.com/IceQ1337/SteamBanChecker/commit/026db8749cfde6f73a1e75f3696ae562aaa67e5f in order to solve https://github.com/IceQ1337/SteamBanChecker/issues/5, but should be implemented again in the future.

**Comment by 45656456kawai** [comment]
Hi, thanks for these awesome scripts I've been using em for a couple of weeks now and so far working great.

I wanted to ask a question about your other project "OverwatchChecker" I've set up around 10 accounts and it does what it claims however I was wondering from where it gets the data about steam ID of The Suspect from the demo file or not? If not then anyway to skip downloading of the demo to save bandwidth? Cheers and Marry Xmas.

**Comment by IceQ1337** [comment]
Coming with Version 2.0.0
