### ISSUE TITLE
No notification

### ISSUE THREAD

**Issue by Waller1337** [IceQ1337/SteamBanChecker#8]
I don't get a notification even though the added accounts got banged :(

**Comment by IceQ1337** [comment]
Please provide as many details as possible. I do not experience this error. Do you get any error messages in the console? Have you entered a valid Steam API Key, Telegram Bot Token and Chat ID?

**Comment by Waller1337** [comment]
No error is displayed in the console. When i type /stats " The database contains a total of 4 profile(s) added by 1 user(s). 0 of them are banned and 4 are still being checked which means a total of 0% of all profiles are banned. You have added 4 profile(s) and 0 (0%) of them are banned." but these accounts are banned.

**Comment by Waller1337** [comment]
After a day from the ban, I got the notification but only the script detected one ban of 4 accounts :|

**Comment by IceQ1337** [comment]
I have tested the script in multiple test environments today and cannot reproduce this bug/error, so if there is one, I am currently unable to fix it as I am only able to guess what's (possibly) wrong.

For now, I leave this issue open for further discussion.

**Comment by IceQ1337** [comment]
Please send me the content of your data/db/profiles.db and your config.json, but make sure to remove all sensitive information from it first.

**Comment by Waller1337** [comment]
Config
{
	"General": {
		"allowRequests": true,
		"messages": "default",
		"checkInterval": 10
	},
	"Steam": {
		"apiKey": ""
	},
	"Telegram": {
		"botToken": "",
		"masterChatID": ""
	},
	"Screenshot": {
		"takeScreenshot": false,
		"sendScreenshot": true,
		"saveScreenshot": true
	}
}

**Comment by Waller1337** [comment]
Profiles.db
{"$$indexCreated":{"fieldName":"SteamID","unique":true,"sparse":false}}
{"SteamID":"76561198000192022","CommunityBanned":false,"VACBanned":false,"NumberOfVACBans":0,"NumberOfGameBans":1,"Tracked":true,"Users":[623362549],"_id":"9mWt78A6dNefuFho"}
{"SteamID":"76561198259812985","CommunityBanned":false,"VACBanned":false,"NumberOfVACBans":0,"NumberOfGameBans":1,"Tracked":true,"Users":[623362549],"_id":"vULRVn5hu8INAA4L"}
{"SteamID":"76561198377627185","CommunityBanned":false,"VACBanned":true,"NumberOfVACBans":1,"NumberOfGameBans":0,"Tracked":true,"Users":[623362549],"_id":"cnKWzQ7o0KChfBUb"}

**Comment by IceQ1337** [comment]
> 
> 
> Profiles.db
> {"$$indexCreated":{"fieldName":"SteamID","unique":true,"sparse":false}}
> {"SteamID":"76561198000192022","CommunityBanned":false,"VACBanned":false,"NumberOfVACBans":0,"NumberOfGameBans":1,"Tracked":true,"Users":[623362549],"_id":"9mWt78A6dNefuFho"}
> {"SteamID":"76561198259812985","CommunityBanned":false,"VACBanned":false,"NumberOfVACBans":0,"NumberOfGameBans":1,"Tracked":true,"Users":[623362549],"_id":"vULRVn5hu8INAA4L"}
> {"SteamID":"76561198377627185","CommunityBanned":false,"VACBanned":true,"NumberOfVACBans":1,"NumberOfGameBans":0,"Tracked":true,"Users":[623362549],"_id":"cnKWzQ7o0KChfBUb"}

What i can see from this is that the bans were applied to the database, but the profiles are still being tracked. This may have happened because you added the account to the list when it was already banned as described under [README.md#how-it-operates](https://github.com/IceQ1337/SteamBanChecker/blob/master/README.md#how-it-operates)

To test if you really don't get any notifications, change `NumberOfGameBans` to `0` for the first two profiles. The last one requires you to change `VACBanned` to `false` and `NumberOfVACBans` to `0`. Once you've made and saved these changes, restart the script and it should send you a notification for all of them. Since you received a notification, I don't think the problem is with your internet connection or with the Telegram bot.

**Comment by Waller1337** [comment]
I changed as you ordered, and I got a notification. Sorry to bother you and thank you. :)
